### PR TITLE
Fix for indexer crash on unique constraint

### LINKED ISSUE #176: Indexer crashing on account destruction
When running evil-tools script for deletion of an account: [script](https://github.com/iotaledger/evil-tools/blob/main/scripts/test_account_implicit.sh) the indexer is crushing with the following error:
```
inx-indexer-1       | 2024-01-11T08:09:20Z      WARNING         /scratch/pkg/indexer/indexer.go:181 UNIQUE constraint failed: accounts.account_id
inx-indexer-1       | [0.037ms] [rows:0] INSERT INTO `accounts` (`account_id`,`output_id`,`amount`,`issuer`,`sender`,`address`,`created_at_slot`,`deleted_at_slot`,`committed`) VALUES ("<binary>","<binary>","1000000000","","","<binary>",48,0,false) 
inx-indexer-1       | 2024-01-11T08:09:20Z      ERROR           ListenToAcceptedTransactions failed: UNIQUE constraint failed: accounts.account_id 
inx-indexer-1       | 2024-01-11T08:09:20Z      INFO    Indexer Stopping AcceptedTransactions ... done 
```

The crush seems to be caused by destroying transaction: account on the input side, basic output on the output.

### PR DESCRIPTION
**Pull request by alexsporn**
Fixes #176

### CODE REVIEW

File: pkg/indexer/account_test.go [hunk 1]
```diff
@@ -96,3 +98,157 @@ func TestIndexer_AccountOutput(t *testing.T) {
...
+			},
+			{
+				OutputID: foundryOutputID,
+				Output:   foundryOutput,
+				BookedAt: 2,
+			},
+		},
+	}
+
+	require.NoError(ts.T, ts.Indexer.AcceptLedgerUpdate(update))
```
Comment (muXxer) [inline pkg/indexer/account_test.go:253]:
```suggestion
	require.NoError(ts.T, ts.Indexer.AcceptLedgerUpdate(update))
	
	ts.requireFound(newOutputID)
	ts.requireFound(foundryOutputID)
```

**Review by muXxer — APPROVED** [review]
